[project]
name = "disspcap"
version = "1.1.1"
description = "Pcap parsing library."
authors = [{ name = "Daniel Uhricek", email = "daniel.uhricek@gypri.cz" }]
requires-python = "~=3.7"
readme = "README.md"
license = "MIT"
dependencies = ["pybind11~=2.2"]

[build-system]
requires = ["setuptools>=42", "wheel", "pybind11~=2.10"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "numpy>=1.21.6",
    "pytest>=7.4.4",
]
